// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgNmFE6NFTJkuVfnF5Ab-obeewMeihyP0',
    appId: '1:1079984203749:android:a92e398b368cda46faf10c',
    messagingSenderId: '1079984203749',
    projectId: 'loginapp-500bb',
    storageBucket: 'loginapp-500bb.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0pVEeGAyFmh0BRLdTgyoDSZYe-92i6oU',
    appId: '1:1079984203749:web:2299f92288646714faf10c',
    messagingSenderId: '1079984203749',
    projectId: 'loginapp-500bb',
    authDomain: 'loginapp-500bb.firebaseapp.com',
    storageBucket: 'loginapp-500bb.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6fwQGn54fNAAQzFA8vHE6A93Gex3WqYI',
    appId: '1:1079984203749:ios:4f88ee581b0f6a12faf10c',
    messagingSenderId: '1079984203749',
    projectId: 'loginapp-500bb',
    storageBucket: 'loginapp-500bb.appspot.com',
    iosBundleId: 'com.example.appProject',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6fwQGn54fNAAQzFA8vHE6A93Gex3WqYI',
    appId: '1:1079984203749:ios:4f88ee581b0f6a12faf10c',
    messagingSenderId: '1079984203749',
    projectId: 'loginapp-500bb',
    storageBucket: 'loginapp-500bb.appspot.com',
    iosBundleId: 'com.example.appProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0pVEeGAyFmh0BRLdTgyoDSZYe-92i6oU',
    appId: '1:1079984203749:web:21684f5b188661d3faf10c',
    messagingSenderId: '1079984203749',
    projectId: 'loginapp-500bb',
    authDomain: 'loginapp-500bb.firebaseapp.com',
    storageBucket: 'loginapp-500bb.appspot.com',
  );

}